### ISSUE TITLE
Example program (example.py) crashing at first run under python 3.9 windows

### ISSUE THREAD

**Issue by clixx-io** [goncalopp/simple-ocr-opencv#38]
C:\users\david\simple-ocr-opencv\simpleocr\__init__.py:28: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif sys.platform is "win32":
showing after BlurProcessor (waiting for input)
showing ContourSegmenter contours (waiting for input)
showing image after segmentation by RawContourSegmenter (waiting for input)
showing segments filtered by LargeFilter (waiting for input)
showing segments filtered by SmallFilter (waiting for input)
showing segments filtered by LargeAreaFilter (waiting for input)
showing segments filtered by ContainedFilter (waiting for input)
Traceback (most recent call last):
  File "example.py", line 15, in <module>
    test_chars, test_classes, test_segments = ocr.ocr(test_image, show_steps=True)
  File "C:\users\david\simple-ocr-opencv\simpleocr\ocr.py", line 73, in ocr
    self.segmenter.display()
  File "C:\users\david\simple-ocr-opencv\simpleocr\processor.py", line 162, in display
    p.display(display_before=False)
  File "C:\users\david\simple-ocr-opencv\simpleocr\segmentation_aux.py", line 83, in display
    draw_lines(copy, self.lines_tops, (0, 0, 255))
  File "C:\users\david\simple-ocr-opencv\simpleocr\opencv_utils.py", line 115, in draw_lines
    cv2.line(image, (0, y), (image.shape[1], y), color, line_width)
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by ituitis-kayaa18** [comment]
same, did you able to solve it?

**Comment by rupert-sch** [comment]
Hello goncallop,

I managed to repair the cv2.line problem by PR #39. Nevertheless, the program runs into more problems under python 3.9:
The next one is in ocr.py, line 30: 
```
TypeError
only integer scalar arrays can be converted to a scalar index
  File "[/home/rupert/Software/OpenCV/simple-ocr-opencv/simpleocr/ocr.py]()", line 30, in reconstruct_chars
    result_string = "".join(map(unichr, classes))
  File "[/home/rupert/Software/OpenCV/simple-ocr-opencv/simpleocr/ocr.py]()", line 76, in ocr
    chars = reconstruct_chars(classes)
  File "[/home/rupert/Software/OpenCV/simple-ocr-opencv/example.py]()", line 15, in <module>
    test_chars, test_classes, test_segments = ocr.ocr(test_image, show_steps=True)
```
Pretty similar in example_grounding.py
```
TypeError
only integer scalar arrays can be converted to a scalar index
  File "[/home/rupert/Software/OpenCV/simple-ocr-opencv/simpleocr/classification.py]()", line 31, in classes_from_numpy
    classes = list(map(unichr, classes))
  File "[/home/rupert/Software/OpenCV/simple-ocr-opencv/simpleocr/grounding.py]()", line 69, in ground
    classes = classes_from_numpy(imagefile.ground.classes)
  File "[/home/rupert/Software/OpenCV/simple-ocr-opencv/example_grounding.py]()", line 10, in <module>
    grounder.ground(new_image, segments)

```
Probably all locations `map(unichr, classes)`. Do you see a solution for these?
Best regards, Rupert

**Comment by goncalopp** [comment]
It's been a while, so I don't exactly remember what the numpy array 
types/shapes of "classes" are, but ultimately you need to convert it to 
a string or list of characters.

The code is still in python2.

`unichr` is just `chr` in python3.

The array conversion problem might have several causes. 
`print(type(classes)); print(classes.shape); print(classes.dtype)` will 
give you valuable debug information.

I wonder if doing a `classes.reshape(-1)` might help.


Thank you for picking this up. If you have time to contribute back your 
changes that would definitely be appreciated by a lot of people that are 
still downloading this despite its age :)

**Comment by zhixuanli** [comment]
Hi everyone, you can change the code in `ocr.py` into this:

```
def reconstruct_chars(classes):
    classes = numpy.asarray(classes, dtype=int)
    result_string = ""
    for cls in classes:
        result_string += str(cls)
    return result_string
```

And this is my output:
```
showing after BlurProcessor (waiting for input)
showing ContourSegmenter contours (waiting for input)
showing image after segmentation by RawContourSegmenter (waiting for input)
showing segments filtered by LargeFilter (waiting for input)
showing segments filtered by SmallFilter (waiting for input)
showing segments filtered by LargeAreaFilter (waiting for input)
showing segments filtered by ContainedFilter (waiting for input)
showing line starts and ends (waiting for input)
showing segments filtered by NearLineFilter (waiting for input)
accuracy: 1.0
OCRed text:
 [51][49][52][49][53][57][50][54][53][51][53][56][57][55][57][51][50][51][56][52][54][50][54][52][51][51][56][51][50][55][57][53][48][50][56][56][52][49][57][55][49][54][57][51][57][57][51][55][53][49][48][53][56][50][48][57][55][52][57][52][52][53][57][50][51][48][55][56][49][54][52][48][54][50][56][54][50][48][56][57][57][56][54][50][56][48][51][52][56][50][53][51][52][50][49][49][55][48][54][55][57][56][50][49][52][56][48][56][54][53][49][51][50][56][50][51][48][54][54][52][55][48][57][51][56][52][52][54][48][57][53][53][48][53][56][50][50][51][49][55][50][53][51][53][57][52][48][56][49][50][56][52][56][49][49][49][55][52][53][48][50][56][52][49][48][50][55][48][49][57][51][56][53][50][49][49][48][53][53][53][57][54][52][52][54][50][50][57][52][56][57][53][52][57][51][48][51][56][49][57][54][52][52][50][56][56][49][48][57][55][53][54][54][53][57][51][51][52][52][54][49][50][56][52][55]

```

**Comment by rupert-sch** [comment]
Hi @zhixuanli,
> you can change the code in `ocr.py`
> 
Thank you! It works for me, too, but I don't know why: My knowledge of Python, CV and OCR is by far too limited...

I came to this program because I want to read out photos like these:
![7seg1](https://user-images.githubusercontent.com/40740682/164890721-6977143a-d665-44d5-b569-e95368d9a228.png)

As far as I understand the processes I need to train and "ground" the picture. Obviously, `test_grounding.py` calls more or other procedures than `example.py`, because it throws an error (only the first?!?) for line 31 in `classification.py`. Can you look into this issue as well and try to fix it?
Thanks a lot!
Rupert
